name: build and push docker image to ECR
on:
  push:
    branches:
      - main
env:
  AWS_REGION : "ap-northeast-1"
permissions:
  id-token: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 2
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_DEV }}:role/github_actions_docker_image_push-ms-user
          role-session-name: PlanSession
          aws-region: ${{ env.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        id: login-ecr
      - name: Set up buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ms-user
        with:
          images: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
          tags: |
            type=raw,value=dev-{{date 'YYYYMMDD-HHmmss' tz='Asia/Tokyo'}}-{{sha}}
      - name: docker build and push ECR
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
      - name: Check for migration file changes
        id: check_migrations
        run: |
          if git diff --name-only HEAD^..HEAD | grep -q "^db/migrations/"; then
            echo "MIGRATION_CHANGED=true" >> $GITHUB_ENV
          else
            echo "MIGRATION_CHANGED=false" >> $GITHUB_ENV
          fi
      - name: Docker meta(for migrate)
        if: env.MIGRATION_CHANGED == 'true'
        id: meta-migrate
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ms-user
        with:
          images: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
          tags: |
            type=raw,value=dev-{{date 'YYYYMMDD-HHmmss' tz='Asia/Tokyo'}}-{{sha}}-migrate
          labels: |
            type=migrate
      - name: docker build and push ECR(for migrate)
        if: env.MIGRATION_CHANGED == 'true'
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          file: ./Dockerfile.migrate
          push: true
          tags: ${{ steps.meta-migrate.outputs.tags }}
          labels: ${{ steps.meta-migrate.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
      - name: Deploy to Lambda
        if: env.MIGRATION_CHANGED == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ms-user
          FUNCTION_NAME: migrate-lambda-ms-user
        run: |
          aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --image-uri ${{ steps.meta-migrate.outputs.tags }}
          # https://docs.aws.amazon.com/cli/latest/reference/lambda/wait/#cli-aws-lambda-wait
          aws lambda wait function-updated-v2 --function-name ${{ env.FUNCTION_NAME }}
      - name: Invoke Lambda for DB Migration
        if: env.MIGRATION_CHANGED == 'true'
        env:
          FUNCTION_NAME: migrate-lambda-ms-user
        run: |
          aws lambda invoke --function-name ${{ env.FUNCTION_NAME }} --payload '{}' response.json
          cat response.json
